# Generated by Django 3.0.2 on 2020-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200606_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_amount',
            field=models.FloatField(default=0, help_text='Amount in liters'),
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='quantity',
            field=models.FloatField(help_text='Quantity in liters'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='current_amount',
            field=models.FloatField(default=0, help_text='Amount in liters'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='price',
            field=models.FloatField(help_text='Price of a liter'),
        ),
    ]
