# Generated by Django 3.2.3 on 2021-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200721_1529'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measure',
            name='unique_size_for_product',
        ),
        migrations.AlterField(
            model_name='productcomposition',
            name='quantity',
            field=models.FloatField(help_text='Quantity to make a liter of product'),
        ),
    ]
